=== magebitcom/magento2-agentic-commerce-module/etc/ac_product_feed_mapping.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="phpClassName">
        <xs:annotation>
            <xs:documentation>
                A string that matches a Fully Qualified Class Name from PHP, especially not starting
                with a backslash as this is an invalid character to start a class name with but a
                somewhat common mistake so this simple type can be used to validate against it
                already
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="(\\?[a-zA-Z_&#x7f;-&#xff;][a-zA-Z0-9_&#x7f;-&#xff;]*)(\\[a-zA-Z_&#x7f;-&#xff;][a-zA-Z0-9_&#x7f;-&#xff;]*)*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="argumentType" abstract="true" mixed="true">
    </xs:complexType>

    <xs:complexType name="const">
        <xs:complexContent>
            <xs:extension base="attributeName" />
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="object">
        <xs:complexContent>
            <xs:extension base="attributeName" />
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="attributeName">
        <xs:annotation>
            <xs:documentation>
                A string that matches an attribute name
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="argumentType" />
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="attributes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="mapping" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="attributeName" name="source_attribute"/>
                                        <xs:element type="attributeName" name="target_attribute"/>
                                        <xs:element type="object" name="formatter" minOccurs="0"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:unique name="uniqueMappingId">
                        <xs:selector xpath="mapping"/>
                        <xs:field xpath="@id"/>
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== magebitcom/magento2-agentic-commerce-module/etc/ac_product_feed_mapping.xml
<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magebit_AgenticCommerce:etc/ac_product_feed_mapping.xsd">
    <attributes>
        <mapping id="enable_search">
            <source_attribute>visibility</source_attribute>
            <target_attribute xsi:type="const">Magebit\AgenticCommerce\Api\Data\Spec\OpenAIFlagsInterface::ENABLE_SEARCH</target_attribute>
            <formatter xsi:type="object">Magebit\AgenticCommerce\Model\Mapping\Formatter\EnableSearch</formatter>
        </mapping>

        <mapping id="enable_checkout">
            <source_attribute xsi:type="object">Magebit\AgenticCommerce\Model\Mapping\Source\EnableCheckout</source_attribute>
            <target_attribute xsi:type="const">Magebit\AgenticCommerce\Api\Data\Spec\OpenAIFlagsInterface::ENABLE_CHECKOUT</target_attribute>
        </mapping>

        <mapping id="id">
            <source_attribute>sku</source_attribute>
            <target_attribute xsi:type="const">Magebit\AgenticCommerce\Api\Data\Spec\ProductInterface::ID</target_attribute>
        </mapping>

        <mapping id="name">
            <source_attribute>name</source_attribute>
            <target_attribute xsi:type="const">Magebit\AgenticCommerce\Api\Data\Spec\ProductInterface::TITLE</target_attribute>
        </mapping>

        <mapping id="description">
            <source_attribute>description</source_attribute>
            <target_attribute xsi:type="const">Magebit\AgenticCommerce\Api\Data\Spec\ProductInterface::DESCRIPTION</target_attribute>
        </mapping>

        <!-- TODO -->
        <mapping id="gtin">
            <source_attribute>sku</source_attribute>
            <target_attribute xsi:type="const">Magebit\AgenticCommerce\Api\Data\Spec\ProductInterface::GTIN</target_attribute>
        </mapping>

        <mapping id="link">
            <source_attribute xsi:type="object">Magebit\AgenticCommerce\Model\Mapping\Source\Url</source_attribute>
            <target_attribute xsi:type="const">Magebit\AgenticCommerce\Api\Data\Spec\ProductInterface::LINK</target_attribute>
        </mapping>

        <!-- Item Information -->
        <mapping id="condition">
            <source_attribute xsi:type="object">Magebit\AgenticCommerce\Model\Mapping\Source\Condition</source_attribute>
            <target_attribute xsi:type="const">Magebit\AgenticCommerce\Api\Data\Spec\ItemInformationInterface::CONDITION</target_attribute>
        </mapping>

        <mapping id="product_category">
            <source_attribute xsi:type="object">Magebit\AgenticCommerce\Model\Mapping\Source\Category</source_attribute>
            <target_attribute xsi:type="const">Magebit\AgenticCommerce\Api\Data\Spec\ItemInformationInterface::PRODUCT_CATEGORY</target_attribute>
        </mapping>

        <mapping id="brand">
            <source_attribute>manufacturer</source_attribute>
            <target_attribute xsi:type="const">Magebit\AgenticCommerce\Api\Data\Spec\ItemInformationInterface::BRAND</target_attribute>
        </mapping>

        <!-- Media Information -->
        <mapping id="image_link">
            <source_attribute xsi:type="object">Magebit\AgenticCommerce\Model\Mapping\Source\Image</source_attribute>
            <target_attribute xsi:type="const">Magebit\AgenticCommerce\Api\Data\Spec\MediaInterface::IMAGE_LINK</target_attribute>
        </mapping>

        <!-- Price Information -->

        <mapping id="price">
            <source_attribute>price</source_attribute>
            <target_attribute xsi:type="const">Magebit\AgenticCommerce\Api\Data\Spec\PriceInterface::PRICE</target_attribute>
            <formatter xsi:type="object">Magebit\AgenticCommerce\Model\Mapping\Formatter\Price</formatter>
        </mapping>

        <mapping id="sale_price">
            <source_attribute xsi:type="object">Magebit\AgenticCommerce\Model\Mapping\Source\FinalPrice</source_attribute>
            <target_attribute xsi:type="const">Magebit\AgenticCommerce\Api\Data\Spec\PriceInterface::SALE_PRICE</target_attribute>
            <formatter xsi:type="object">Magebit\AgenticCommerce\Model\Mapping\Formatter\Price</formatter>
        </mapping>

        <mapping id="sale_price_effective_date">
            <source_attribute xsi:type="object">Magebit\AgenticCommerce\Model\Mapping\Source\SalePriceEffectiveDate</source_attribute>
            <target_attribute xsi:type="const">Magebit\AgenticCommerce\Api\Data\Spec\PriceInterface::SALE_PRICE_EFFECTIVE_DATE</target_attribute>
        </mapping>

        <!-- Availability & Inventory -->

        <mapping id="availability">
            <source_attribute xsi:type="object">Magebit\AgenticCommerce\Model\Mapping\Source\StockStatus</source_attribute>
            <target_attribute xsi:type="const">Magebit\AgenticCommerce\Api\Data\Spec\AvailabilityInterface::AVAILABILITY</target_attribute>
        </mapping>

        <mapping id="inventory_quantity">
            <source_attribute xsi:type="object">Magebit\AgenticCommerce\Model\Mapping\Source\StockQuantity</source_attribute>
            <target_attribute xsi:type="const">Magebit\AgenticCommerce\Api\Data\Spec\AvailabilityInterface::INVENTORY_QUANTITY</target_attribute>
        </mapping>

        <!-- Merchant Info -->

        <mapping id="seller_name">
            <source_attribute xsi:type="object">Magebit\AgenticCommerce\Model\Mapping\Source\SellerName</source_attribute>
            <target_attribute xsi:type="const">Magebit\AgenticCommerce\Api\Data\Spec\MerchantInfoInterface::SELLER_NAME</target_attribute>
        </mapping>

        <mapping id="seller_url">
            <source_attribute xsi:type="object">Magebit\AgenticCommerce\Model\Mapping\Source\SellerUrl</source_attribute>
            <target_attribute xsi:type="const">Magebit\AgenticCommerce\Api\Data\Spec\MerchantInfoInterface::SELLER_URL</target_attribute>
        </mapping>
    </attributes>
</config>
